name: Suggest Mod
description: Suggest mods to be added to Gem Realms
title: "[📦]: "
labels: ["Module"]
body:
  - type: markdown
    attributes:
      value: |
        MOD SUGGESTION

  - type: checkboxes
    id: code-of-conduct
    attributes:
      label: "Code Of Conduct"
      options:
        - label: "See (LINK WILL BE ADDED IN FUTURE) if someone already suggested a mod that you are going to suggest. \nFOR NOW check out the issues"
          required: true
        - label: "For MetalType, The suggested mod must contain variant blocks of IRON or GOLD"
          required: true
        - label: "For GemType, The suggested mod must contain variant blocks of either DIAMOND or EMERALD"
          required: true
        - label: "For CrystalType, The suggested mod must contain variant blocks of AMETHYST,"
          required: true
        - label: "For DustType, The suggested mod must contain variant blocks of REDSTONE_BLOCK"
          required: true

  - type: input
    id: curseforge-normal
    attributes:
      label: Curseforge (Normal)
      description: "The link for mod's Curseforge with Forge & Fabric"
      placeholder: ex. https://www.curseforge.com/minecraft/mc-mods/giacomos-bookshelf
    validations:
      required: true

  - type: input
    id: curseforge-fabric
    attributes:
      label: Curseforge-Fabric (Optional)
      description: "If the mod has 2 Curseforge pages for Forge & Fabric, then use Fabric Link here"
      placeholder: ex. https://www.curseforge.com/minecraft/mc-mods/giacomos-bookshelf
    validations:
      required: false

  - type: checkboxes
    id: version-loader-availability
    attributes:
      label: Version Loader Availability
      description: "Multiple Selection: which version & loader is the mod available in?"
      options:
        - label: "1.20.1 | FABRIC"
        - label: "1.21.1 | FABRIC"
        - label: "1.20.1 | FORGE"
        - label: "1.21.1 | NEOFORGE"

  - type: input
    id: modid
    attributes:
      label: MODID
      description: "MODID of the mod"
      placeholder: somemoreblocks
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: "Types"
      description: "Type of blocks are in the mod?"
      placeholder: "For MetalType (Variants of Regular Block): \n- somemoreblocks:cracked_cut_gold\n- somemoreblocks:cut_gold\n- somemoreblocks:gold_pillar\n- somemoreblocks:cracked_gold_bricks\n- somemoreblocks:gold_bricks"
    validations:
        required: true

  - type: textarea
    attributes:
      label: Optional Information
      description: |
        A note that we should keep in mind regarding the mod
      placeholder: "ex: There is an item, gold_sheet used for crafting these blocks in the list above."
    validations:
      required: false
